// Serves a decklist as Tabletop Simulator JSON, so a TTS mod (or a Lua
// WebRequest) can load it straight from a URL instead of a downloaded file:
//
//   /lists/:event/:id/tts.json
//   /majors/:event/:id/tts.json
//
// Same JSON the page's TTS download button produces — both go through
// generateTTSJson. Decks come pre-resolved from
// netlify/edge-functions/lib/tts-data.js, generated by
// scripts/gen-tts-manifest.mjs, so nothing here touches the card database.

import data from './lib/tts-data.js'
import { generateTTSJson } from '../../src/js/tts_export.js'

export const config = { pattern: '^/(lists|majors)/[^/]+/[^/]+/tts\\.json$' }

const HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  // TTS fetches from outside any browser, but a web-based importer would need it.
  'access-control-allow-origin': '*',
  'cache-control': 'public, max-age=300',
}

export default async (request) => {
  const [, section, event, standing] = new URL(request.url).pathname.split('/')
  const deck = data[section]?.[`${decodeURIComponent(event)}/${decodeURIComponent(standing)}`]
  if (!deck) {
    return new Response(JSON.stringify({ error: 'Decklist not found' }), { status: 404, headers: HEADERS })
  }

  const card = ([i, qty]) => ({ ...data.cards[i], qty })
  const json = generateTTSJson(
    deck.n,
    deck.f == null ? null : data.cards[deck.f],
    deck.m.map(card),
    deck.s.map(card),
  )
  // Header values must be Latin-1, and deck names carry emoji and curly quotes:
  // an ASCII fallback, plus the real name RFC 5987-encoded for browsers that save it.
  const ascii = deck.n.replace(/[^\x20-\x7e]|["\\]/g, '').trim() || 'deck'
  const disposition = `inline; filename="${ascii}.json"; filename*=UTF-8''${encodeURIComponent(`${deck.n}.json`)}`
  return new Response(JSON.stringify(json), {
    headers: { ...HEADERS, 'content-disposition': disposition },
  })
}
