// Injects per-URL Open Graph / Twitter meta tags into the SPA's index.html for
// /lists routes, so shared links get a rich preview (title, description, and a
// character-card image) instead of the generic site card. Crawlers don't run
// the app's JS, so the tags must be present in the served HTML — this does that
// at the edge. Regular visitors get the same HTML plus the tags, then the SPA
// boots normally.
//
// Preview text/images come from netlify/edge-functions/lib/preview-data.js,
// generated by scripts/gen-preview-manifest.mjs.

import manifest, { SITE_BASE } from './lib/preview-data.js'

export const config = { path: '/lists/*' }

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// Map a /lists pathname to its preview entry, or null when there's nothing richer
// than the site default to show.
function lookup(pathname) {
  const parts = pathname.replace(/^\/+|\/+$/g, '').split('/')
  if (parts[0] !== 'lists') return null
  if (parts.length === 1) return manifest.index
  const event = decodeURIComponent(parts[1])
  if (parts.length === 2) return manifest.events[event] || null
  const standing = decodeURIComponent(parts[2])
  return manifest.players[`${event}/${standing}`] || null
}

function buildTags(meta, canonicalUrl) {
  const tags = [
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="BuildUVS">`,
    `<meta property="og:url" content="${esc(canonicalUrl)}">`,
    `<meta property="og:title" content="${esc(meta.title)}">`,
    `<meta name="twitter:title" content="${esc(meta.title)}">`,
    // Preview image is the portrait character card, so the small square card.
    `<meta name="twitter:card" content="summary">`,
  ]
  if (meta.description) {
    tags.push(
      `<meta name="description" content="${esc(meta.description)}">`,
      `<meta property="og:description" content="${esc(meta.description)}">`,
      `<meta name="twitter:description" content="${esc(meta.description)}">`,
    )
  }
  if (meta.image) {
    tags.push(
      `<meta property="og:image" content="${esc(meta.image)}">`,
      `<meta name="twitter:image" content="${esc(meta.image)}">`,
      `<meta property="og:image:alt" content="${esc(meta.title)}">`,
    )
  }
  tags.push(`<title>${esc(meta.title)}</title>`)
  return tags.join('\n    ')
}

export default async (request, context) => {
  const res = await context.next()
  if (!(res.headers.get('content-type') || '').includes('text/html')) return res

  const url = new URL(request.url)
  const meta = lookup(url.pathname)
  if (!meta) return res

  let html = await res.text()
  // Drop the static <title> and any static description so ours are authoritative.
  html = html
    .replace(/<title>[\s\S]*?<\/title>/i, '')
    .replace(/<meta\s+name="description"[^>]*>/i, '')

  const canonicalUrl = SITE_BASE + url.pathname
  const injected = html.replace(/<\/head>/i, `    ${buildTags(meta, canonicalUrl)}\n  </head>`)

  const headers = new Headers(res.headers)
  headers.delete('content-length') // body length changed
  return new Response(injected, { status: res.status, headers })
}
